image: registry.gitlab.com/xcompass/kubernetes-deploy

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2375
  # improve docker build performance
  DOCKER_DRIVER: overlay
  # Application deployment domain
  KUBE_DOMAIN: apps.ctlt.ubc.ca
  # helm chart to deploy
  DEPLOYMENT_MANIFEST: ctlt/statspace
  # Build
  app__image__tag: $CI_BUILD_REF_NAME
  CI_REGISTRY_IMAGE: ubcctlt/dspace

stages:
  - build
  - review
  - staging
  - production

build_image:
  stage: build
  script:
    - command build

production:
  stage: production
  variables:
    DEPLOYMENT_VALUE_FILE: configuration/statspace/values_prod.yaml
    GIT_STRATEGY: none
  before_script:
    - source docker-entrypoint.sh
    - git clone git@repo.code.ubc.ca:devops/configuration.git
  script:
    - command deploy-helm
  environment:
    name: production
    url: http://statspace.elearning.ubc.ca
  when: manual
  only:
    - statspace
staging:
  stage: staging
  variables:
    DEPLOYMENT_VALUE_FILE: configuration/statspace/values_staging.yaml
    GIT_STRATEGY: none
  before_script:
    - source docker-entrypoint.sh
    - git clone git@repo.code.ubc.ca:devops/configuration.git
  script:
    - command deploy-helm
  environment:
    name: staging
    url: http://statspace.stg.$KUBE_DOMAIN
  only:
    - statspace
review:
  stage: review
  variables:
    DEPLOYMENT_VALUE_FILE: configuration/statspace/values_review.yaml
    GIT_STRATEGY: none
  before_script:
    - source docker-entrypoint.sh
    - git clone git@repo.code.ubc.ca:devops/configuration.git
  script:
    - command deploy-helm
  environment:
    name: $ENV_NAME
    url: http://statspace.$CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
    on_stop: stop_review
  only:
    - branches
  except:
    - statspace
stop_review:
  stage: review
  variables:
    GIT_STRATEGY: none
  script:
    - command destroy-helm
  environment:
    name: $ENV_NAME
    action: stop
  when: manual
  only:
    - triggers
